name = "gkuga-remix-examples-cloudflarepages"
pages_build_output_dir = "build/client"
compatibility_date = "2024-09-25"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "cloudflarepages"
database_id = "9f3a2ba8-21ef-4367-941e-a795af27f5bc"
